### ISSUE TITLE
dbl.oisd.nl

### ISSUE THREAD

**Issue by sjhgvr** [dead-hosts/dev-center#5]
a mirror for dbl.oisd.nl blocklist
  * https://github.com/ookangzheng/dbl-oisd-nl
  * Lists to test:
    * https://github.com/ookangzheng/dbl-oisd-nl/blob/master/dbl.txt?raw=true

**Comment by funilrys** [comment]
Hi @sjhgvr is it okay if I set up everything with https://dbl.oisd.nl/ ? 

Cheers,
Nissar

**Comment by sjhgvr** [comment]
Sure. Thanks

**Comment by funilrys** [comment]
:heavy_check_mark: : https://github.com/dead-hosts/domain_blocklist_web_dbl-oisd-nl

**Comment by sjhgvr** [comment]
Sorry for reopening, but I would not want to open a new issue.  

I am doing DNS checking myself, but I thought this would be a lot faster.  
For now it seems wayyyy slow.  (190 checked in 5 hours?, there's over 1.5 million to do, that would take 4,5 years?) Or maybe I'm wrong? Otherwise, I'm not sure what the point of this is exactly.  
I might have been foolish/selfish to think this service would help me? I'm sorry.  

If it really is this slow, delete everything and pretend this didn't happen? And throw something at me that hurts, for me using up your precious time?

**Comment by funilrys** [comment]
Moving to your machine will be way faster if you don't want to wait. In the future, a machine with less restriction and a bit more power than the one of Travis CI will be used. Indeed, we run a session of 10-15 minutes then save and rerun for 10-15 minutes ... But Travis CI allows us to only run 5 units at a time. So, as you're list is not the only one ([cf](https://travis-ci.org/dead-hosts)) it takes some time.

But as it cost a lot of time to maintain (even behind automation) and I do that for free in my free time, don't wait for that. 

If you have your own machine, run PyFunceble with the following configuration and it will be all right and as fast as possible:
```yaml
timeout: 3 # Set the timeout to use to 3 seconds.
generate_complements: false # Don't find and test for complements.
generate_hosts: false # Don't generate a hosts file as output.
idna_conversion: false # Don't convert to IDNA
no_special: true # Don't use SPECIAL rules
no_whois: true # Don't request WHOIS record
plain_list_domain: true # Give us a plain list of domains as output.
whois_database: false  # Disable the WHOIS record database
```

Repo deletion is scheduled.

If you need more information and something isn't clear with the way PyFunceble works, please let me know.

Cheers,
Nissar
